name = "qqai"
main = "worker.js"
compatibility_date = "2026-06-24"
compatibility_flags = [ "nodejs_compat" ]

[browser]
binding = "MYBROWSER"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "QQ_STORE"
id = "bf716105d0f6412fa97daad4e0f544d2"

[[vectorize]]
binding = "VECTORIZE"
index_name = "qqai"

[vars]
BACKGROUND_BROWSER_TIMEOUT = "60"
DEVELOPER_ID = "3569028262"
