// Final responsive layout layer for the Portal.
// This is intentionally injected after all feature clients so it owns the final cascade.

function injectPortalLayoutClient(html) {
  let source = String(html || "");
  if (!source || source.includes("qqai-portal-layout-v274")) return source;
  const style = `<style id="qqai-portal-layout-v274">
:root{--qqai-sidebar-width:248px;--qqai-control-height:44px;--qqai-content-width:1440px}
html{scroll-behavior:smooth}body{line-height:1.5}.app,.main,.content,.view,.grid,.card,.item{min-width:0}.sidebar{width:var(--qqai-sidebar-width)!important;padding:16px 13px!important}.main{margin-left:var(--qqai-sidebar-width)!important;width:auto!important}.content{width:100%!important;max-width:var(--qqai-content-width)!important;padding:24px clamp(18px,2.2vw,34px) 36px!important}.topbar{min-height:72px!important;height:auto!important;padding:12px clamp(18px,2.2vw,34px)!important;display:grid!important;grid-template-columns:minmax(220px,1fr) minmax(420px,auto)!important;align-items:center!important;gap:16px!important;position:sticky!important;top:0!important}.topbar>.row{min-width:0!important;flex-wrap:nowrap!important}.topbar h2{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.top-actions{display:grid!important;grid-template-columns:minmax(220px,1fr) auto auto!important;align-items:center!important;gap:9px!important;width:min(680px,100%)!important;justify-self:end!important}.top-actions select,.top-actions>.btn{width:100%!important;max-width:none!important;height:var(--qqai-control-height)!important;margin:0!important}
.view>.section-head,.ops-integrated-block>.section-head{align-items:center!important;margin-bottom:18px!important}.section-head>div{min-width:0}.section-head p{max-width:820px;line-height:1.65}.section-head>.row{justify-content:flex-end}.grid{align-items:start}.card{padding:20px!important;border-radius:16px!important}.list{gap:12px!important}.item{padding:14px 15px!important}.item-head{align-items:center}.field{min-width:0}.field input,.field select,.field textarea,.qqai-modal-input{width:100%;max-width:100%}.field input,.field select,.top-actions select,.suite-batch-controls input,.suite-batch-controls select,.suite-sticker-form input,.suite-decision-filters input,.suite-decision-filters select,.ww-action input,.ww-action select{min-height:var(--qqai-control-height)}.btn{min-height:var(--qqai-control-height);display:inline-flex;align-items:center;justify-content:center;line-height:1.2}.switch,.member-toggle{min-height:36px}.code,pre,.log-details pre,.conversation-detail pre,.suite-decision-detail{max-width:100%;overflow:auto;overflow-wrap:anywhere}.qqai-modal{overflow:auto}.qqai-modal-card{max-height:min(88dvh,900px);overflow:auto}.toast{overflow-wrap:anywhere}
.member-console-toolbar{grid-template-columns:minmax(220px,.9fr) minmax(280px,1.1fr)!important}.member-console-filters{grid-template-columns:repeat(4,minmax(150px,1fr)) auto auto!important}.member-directory-row{grid-template-columns:minmax(220px,1.35fr) minmax(190px,.75fr) auto!important}.member-action-row{grid-template-columns:minmax(220px,1fr) minmax(190px,.7fr) minmax(360px,1.45fr)!important}.member-actions{justify-content:flex-end}.relationship-direct{grid-template-columns:repeat(2,minmax(200px,1fr)) auto auto!important}.relationship-row{grid-template-columns:minmax(240px,1fr) auto!important}
.suite-grid{grid-template-columns:repeat(auto-fit,minmax(210px,1fr))!important}.suite-batch-controls,.suite-sticker-form,.suite-decision-filters,.suite-profile-flags{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(170px,1fr))!important;gap:10px!important;align-items:end!important}.suite-batch-controls>*,.suite-sticker-form>*,.suite-decision-filters>*,.suite-profile-flags>*{min-width:0!important;width:100%!important;margin:0!important}.suite-sticker-row,.suite-policy-row{grid-template-columns:minmax(240px,1fr) auto!important}
.cleanup-summary{grid-template-columns:repeat(auto-fit,minmax(130px,1fr))!important}.cleanup-policy{grid-template-columns:repeat(auto-fit,minmax(165px,1fr))!important}.cleanup-filters,.member-data-toolbar,.cleanup-head-actions{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(180px,1fr))!important;gap:10px!important}.cleanup-filters>*,.member-data-toolbar>*,.cleanup-head-actions>*{min-width:0!important;width:100%!important;margin:0!important}.cleanup-row{grid-template-columns:auto minmax(230px,1.15fr) minmax(160px,.55fr) minmax(260px,1.2fr)!important}.member-data-row{grid-template-columns:auto minmax(220px,.85fr) minmax(320px,1.4fr)!important}
.ww-create{margin-bottom:14px}.ww-layout{grid-template-columns:minmax(0,1.2fr) minmax(340px,.8fr)!important;gap:16px!important;align-items:start}.ww-grid{grid-template-columns:repeat(auto-fit,minmax(170px,1fr))!important;align-items:end}.ww-grid label{min-width:0}.ww-role-pool{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))!important;max-height:340px;overflow:auto;padding:4px}.ww-log{max-height:430px!important}.ww-log-row{border-color:var(--line)!important;overflow-wrap:anywhere}.ww-action{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:9px!important}.ww-action .btn,.ww-action input{grid-column:1/-1}.ww-secret{overflow-wrap:anywhere}
@media(max-width:1180px){.member-console-filters{grid-template-columns:repeat(3,minmax(150px,1fr))!important}.member-action-row{grid-template-columns:minmax(220px,1fr) minmax(180px,.65fr)!important}.member-action-row>.member-actions{grid-column:1/-1;justify-content:flex-start}.ww-layout{grid-template-columns:1fr!important}}
@media(max-width:1024px){body.sidebar-open{overflow:hidden}.sidebar{width:min(88vw,340px)!important}.main{margin-left:0!important;width:100%!important}.topbar{position:relative!important;top:auto!important;grid-template-columns:1fr!important;align-items:stretch!important;padding:12px!important;gap:10px!important}.topbar>.row{display:grid!important;grid-template-columns:48px minmax(0,1fr)!important;gap:10px!important;align-items:center!important}.top-actions{width:100%!important;max-width:none!important;justify-self:stretch!important;grid-template-columns:minmax(0,1fr) minmax(118px,.34fr) minmax(118px,.34fr)!important}.content{max-width:none!important;padding:16px 14px calc(28px + env(safe-area-inset-bottom))!important}.span-3,.span-4,.span-5,.span-6,.span-7,.span-8,.span-12{grid-column:1/-1!important}.card{padding:16px!important}.member-console-toolbar,.member-console-filters{grid-template-columns:repeat(2,minmax(0,1fr))!important}.member-directory-row,.member-action-row,.relationship-direct,.relationship-row,.cleanup-row,.member-data-row{grid-template-columns:1fr!important}.member-actions,.relationship-actions{justify-content:flex-start}.member-actions input[type="number"]{width:min(180px,100%)!important}.cleanup-row>label,.member-data-row>label{justify-self:start}.suite-sticker-row,.suite-policy-row{grid-template-columns:1fr!important}}
@media(max-width:700px){.view>.section-head,.ops-integrated-block>.section-head,.section-head.compact{display:grid!important;grid-template-columns:1fr!important;align-items:start!important;gap:12px!important}.section-head>.row,.section-head>.btn,.section-head.compact>.row{width:100%;justify-content:stretch!important}.section-head>.row>.btn,.section-head>.btn{flex:1 1 160px}.top-actions{grid-template-columns:repeat(2,minmax(0,1fr))!important}.top-actions select{grid-column:1/-1!important}.member-console-toolbar,.member-console-filters,.cleanup-filters,.member-data-toolbar,.cleanup-head-actions,.suite-batch-controls,.suite-sticker-form,.suite-decision-filters,.suite-profile-flags{grid-template-columns:1fr!important}.member-actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;width:100%}.member-actions>*{width:100%!important;margin:0!important}.relationship-actions{display:grid!important;grid-template-columns:1fr!important}.ww-grid,.ww-action{grid-template-columns:1fr!important}.ww-action>*{grid-column:1!important}.ww-role-pool{grid-template-columns:repeat(2,minmax(0,1fr))!important}.overview-hero-actions,.qqai-modal-actions{display:grid!important;grid-template-columns:1fr!important}.overview-hero-actions .btn,.qqai-modal-actions .btn{width:100%}}
@media(max-width:430px){.top-actions{grid-template-columns:1fr!important}.top-actions select,.top-actions>.btn{grid-column:1!important}.content{padding-left:10px!important;padding-right:10px!important}.card{padding:14px!important}.member-actions{grid-template-columns:1fr!important}.ww-role-pool{grid-template-columns:1fr!important}.status-card{align-items:flex-start}.section-head h2{font-size:21px!important}}
</style>`;
  const script = `<script id="qqai-portal-layout-client-v274">(function(){document.documentElement.dataset.portalLayout="2.7.4";})();</script>`;
  source = source.includes("</head>") ? source.replace("</head>", style + "\n</head>") : style + source;
  source = source.includes("</body>") ? source.replace("</body>", script + "\n</body>") : source + script;
  return source;
}

export { injectPortalLayoutClient };
