// Canonical authenticated Portal presentation.
// The visible core shell is a top app bar + three first-class surfaces.
// Legacy feature markup remains only as plugin-owned compatibility content.

function injectPortalLayoutClient(html) {
  let source = String(html || "");
  if (!source || source.includes("qqai-portal-layout-v400")) return source;
  const style = `<style id="qqai-portal-layout-v400">
:root{
  color-scheme:light;
  --portal-bg:#f5f7fb;--portal-panel:#ffffff;--portal-panel2:#f0f4f9;--portal-panel3:#e8eef6;
  --portal-text:#121c2f;--portal-muted:#66748b;--portal-line:#dce4ef;--portal-line-strong:#c6d1df;
  --portal-primary:#376df5;--portal-primary2:#805cf5;--portal-primary-soft:#eaf0ff;--portal-primary-text:#214abf;
  --portal-ok:#137b5d;--portal-warn:#a86300;--portal-bad:#bd3850;
  --portal-shadow:0 14px 38px rgba(30,47,82,.08);--portal-shadow-lg:0 28px 80px rgba(25,40,75,.14);
  --portal-radius:18px;--portal-control:42px;
  --bg:var(--portal-bg);--panel:var(--portal-panel);--panel2:var(--portal-panel2);--panel3:var(--portal-panel3);
  --text:var(--portal-text);--muted:var(--portal-muted);--line:var(--portal-line);--line-strong:var(--portal-line-strong);
  --primary:var(--portal-primary);--primary-soft:var(--portal-primary-soft);--primary-text:var(--portal-primary-text);
  --ok:var(--portal-ok);--warn:var(--portal-warn);--bad:var(--portal-bad);--shadow:var(--portal-shadow);--shadow-lg:var(--portal-shadow-lg)
}
:root[data-theme="dark"]{
  color-scheme:dark;
  --portal-bg:#080b12;--portal-panel:#101722;--portal-panel2:#17202e;--portal-panel3:#202c3c;
  --portal-text:#f0f4fa;--portal-muted:#97a6bb;--portal-line:#29374a;--portal-line-strong:#3a4b62;
  --portal-primary:#72a3ff;--portal-primary2:#9b7cff;--portal-primary-soft:#1c315f;--portal-primary-text:#c2d2ff;
  --portal-ok:#4bcca2;--portal-warn:#e6ab57;--portal-bad:#ff7b91;
  --portal-shadow:0 16px 42px rgba(0,0,0,.24);--portal-shadow-lg:0 30px 90px rgba(0,0,0,.38)
}
*{box-sizing:border-box}html{background:var(--portal-bg);scroll-behavior:smooth}body{margin:0;background:var(--portal-bg)!important;color:var(--portal-text)!important;line-height:1.55}
html,body,.app,.main,.content,.view,.grid,.card,.item{min-width:0;max-width:100%}body:before{content:"";position:fixed;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(circle at 78% -10%,color-mix(in srgb,var(--portal-primary) 10%,transparent),transparent 34rem),linear-gradient(180deg,color-mix(in srgb,var(--portal-panel2) 18%,transparent),transparent 32rem)}
.hidden{display:none!important}.muted{color:var(--portal-muted)!important}button,input,select,textarea{font:inherit}.qqai-brand-logo{display:block;flex:0 0 auto}

/* New authenticated shell */
.portal-app{min-height:100dvh!important;display:block!important}.portal-appbar{position:sticky;top:0;z-index:60;width:100%;background:color-mix(in srgb,var(--portal-panel) 92%,transparent);backdrop-filter:blur(22px);border-bottom:1px solid var(--portal-line);box-shadow:0 6px 24px rgba(28,43,76,.035)}
.portal-appbar-inner{width:min(1480px,calc(100% - 32px));min-height:76px;margin:auto;display:grid;grid-template-columns:auto minmax(310px,1fr) auto;align-items:center;gap:20px}.portal-brand{display:flex;align-items:center;gap:11px;text-decoration:none;color:var(--portal-text);white-space:nowrap}.portal-brand-logo{width:44px;height:44px}.portal-brand span{display:grid}.portal-brand b{font-size:14px;letter-spacing:-.015em}.portal-brand small{font-size:9px;letter-spacing:.10em;color:var(--portal-muted);margin-top:2px}
.portal-primary-nav{display:flex!important;align-items:center!important;justify-content:center!important;gap:5px!important;min-width:0!important;overflow:visible!important;padding:0!important}.portal-primary-nav>button[data-view]{min-height:42px;border:1px solid transparent;border-radius:11px;background:transparent;color:var(--portal-muted);padding:9px 15px;font-weight:780;cursor:pointer;white-space:nowrap}.portal-primary-nav>button[data-view]:hover{background:var(--portal-panel2);color:var(--portal-text)}.portal-primary-nav>button[data-view].active{background:var(--portal-primary-soft);color:var(--portal-primary-text);border-color:color-mix(in srgb,var(--portal-primary) 22%,var(--portal-line))}
.plugin-compat-nav,.portal-primary-nav>.qqai-nav-entry,.portal-primary-nav>.nav-group{display:none!important}.portal-header-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;min-width:0}.portal-header-actions select{width:132px}.portal-header-actions .btn{white-space:nowrap}.portal-header-actions .identity-card{max-width:150px;min-width:92px;padding:7px 9px;border:1px solid var(--portal-line);border-radius:10px;background:var(--portal-panel2);font-size:10px;line-height:1.35;overflow:hidden}.portal-header-actions .identity-card b,.portal-header-actions .identity-card span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.portal-header-actions .identity-card span{color:var(--portal-muted)}.portal-logout{min-width:62px}.portal-rights{width:min(1480px,calc(100% - 32px));margin:-2px auto 7px;text-align:right;color:var(--portal-muted);font-size:8px;letter-spacing:.04em}.portal-menu{display:none!important}
.sidebar-backdrop{display:none}.portal-main,.main{margin:0!important;min-height:calc(100dvh - 92px)!important;width:100%!important}.portal-subbar,.topbar{position:relative!important;top:auto!important;z-index:1!important;width:min(1480px,calc(100% - 32px))!important;min-height:72px!important;height:auto!important;margin:0 auto!important;padding:22px 0 12px!important;border:0!important;background:transparent!important;backdrop-filter:none!important;display:flex!important;align-items:end!important;justify-content:space-between!important;gap:18px!important}.portal-page-heading h2{margin:2px 0 0;font-size:21px;letter-spacing:-.03em}.top-kicker{font-size:9px;letter-spacing:.16em;color:var(--portal-primary);font-weight:900}.top-actions{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;width:auto!important}.top-actions select,.top-actions>.btn,.portal-header-actions select{height:var(--portal-control);border:1px solid var(--portal-line);border-radius:10px;background:var(--portal-panel);color:var(--portal-text);padding:0 10px}
.portal-content,.content{width:min(1480px,calc(100% - 32px))!important;margin:0 auto!important;padding:10px 0 64px!important}.view{display:none}.view.active{display:block}

/* Rebuilt core home */
.portal-home-hero{min-height:430px;border:1px solid var(--portal-line);border-radius:28px;background:linear-gradient(145deg,var(--portal-panel),color-mix(in srgb,var(--portal-primary-soft) 34%,var(--portal-panel)));box-shadow:var(--portal-shadow);padding:clamp(28px,5vw,58px);display:grid;grid-template-columns:minmax(0,1.18fr) minmax(320px,.82fr);gap:34px;align-items:center;overflow:hidden;position:relative}.portal-home-hero:after{content:"";position:absolute;right:-120px;top:-150px;width:420px;height:420px;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--portal-primary) 18%,transparent),transparent 68%);pointer-events:none}.portal-home-copy{position:relative;z-index:1}.portal-home-mark{display:flex;align-items:center;gap:12px;color:var(--portal-primary);font-size:10px;letter-spacing:.16em;font-weight:900}.portal-home-logo{width:54px;height:54px}.portal-home-copy h1{max-width:830px;margin:19px 0 14px;font-size:clamp(38px,5.7vw,72px);line-height:.99;letter-spacing:-.06em;color:var(--portal-text)}.portal-home-copy p{max-width:700px;margin:0;color:var(--portal-muted);font-size:15px;line-height:1.75}.portal-home-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:25px}.portal-home-orbit{position:relative;min-height:310px;display:grid;place-items:center}.orbit-core{width:150px;height:150px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,var(--portal-primary),var(--portal-primary2));color:#fff;font-weight:950;letter-spacing:.14em;box-shadow:0 20px 60px color-mix(in srgb,var(--portal-primary) 28%,transparent)}.portal-home-orbit:before,.portal-home-orbit:after{content:"";position:absolute;border:1px solid color-mix(in srgb,var(--portal-primary) 28%,var(--portal-line));border-radius:50%}.portal-home-orbit:before{width:250px;height:250px}.portal-home-orbit:after{width:310px;height:310px;opacity:.55}.orbit-chip{position:absolute;border:1px solid var(--portal-line);border-radius:999px;background:var(--portal-panel);box-shadow:var(--portal-shadow);padding:8px 11px;font-size:9px;font-weight:900;color:var(--portal-muted)}.chip-a{left:5%;top:25%}.chip-b{right:3%;top:28%}.chip-c{bottom:9%;left:42%}
.portal-core-status{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:16px 0}.portal-status-card{display:grid;grid-template-columns:44px minmax(0,1fr);gap:12px;align-items:center;padding:16px;border:1px solid var(--portal-line);border-radius:16px;background:var(--portal-panel)}.portal-status-icon{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;background:var(--portal-primary-soft);color:var(--portal-primary-text);font-size:10px;font-weight:900}.portal-status-card small,.portal-status-card em{display:block;color:var(--portal-muted);font-size:10px;font-style:normal}.portal-status-card b{display:block;font-size:15px;margin:2px 0}.portal-home-grid{display:grid;grid-template-columns:minmax(0,1.18fr) minmax(320px,.82fr);gap:16px}.boundary-list{display:grid;gap:9px}.boundary-list>div{display:grid;grid-template-columns:34px minmax(0,1fr);column-gap:10px;padding:12px;border:1px solid var(--portal-line);border-radius:12px;background:var(--portal-panel2)}.boundary-list>div>span{grid-row:1/3;width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:var(--portal-primary-soft);color:var(--portal-primary-text);font-size:9px;font-weight:900}.boundary-list b{font-size:12px}.boundary-list small{color:var(--portal-muted);font-size:10px;margin-top:2px}

/* Core plugin/account surfaces */
.section-head{display:flex!important;align-items:flex-start!important;justify-content:space-between!important;gap:16px!important;margin-bottom:18px!important}.section-head.compact{margin-bottom:13px!important}.section-head h2{margin:0 0 5px!important;font-size:28px!important;letter-spacing:-.035em!important}.section-head h3{margin:0 0 5px!important}.section-head p{margin:0!important;color:var(--portal-muted)!important;max-width:850px!important}.plugin-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:12px}.plugin-grid.compact{grid-template-columns:repeat(2,minmax(0,1fr))}.plugin-card{display:grid;grid-template-columns:46px minmax(0,1fr) auto;gap:12px;align-items:center;border:1px solid var(--portal-line);border-radius:15px;background:var(--portal-panel);padding:15px;min-width:0}.plugin-card.compact{grid-template-columns:40px minmax(0,1fr)}.plugin-card.compact>.plugin-actions{display:none!important}.plugin-card.disabled{opacity:.62}.plugin-icon{width:44px;height:44px;display:grid;place-items:center;border-radius:12px;background:var(--portal-primary-soft);color:var(--portal-primary-text);font-size:12px;font-weight:900}.plugin-card.compact .plugin-icon{width:38px;height:38px}.plugin-card-head{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.plugin-card h3{margin:0!important;font-size:14px!important}.plugin-card p{margin:5px 0 0;color:var(--portal-muted);font-size:11px;line-height:1.5}.plugin-badge,.plugin-state{border:1px solid var(--portal-line);border-radius:999px;background:var(--portal-panel2);color:var(--portal-muted);padding:3px 7px;font-size:8px;font-weight:800}.plugin-state.on{color:var(--portal-ok);border-color:color-mix(in srgb,var(--portal-ok) 30%,var(--portal-line))}.plugin-actions{display:flex;gap:7px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.account-grid{margin-bottom:16px}.identity-summary{padding:14px;border:1px solid var(--portal-line);border-radius:12px;background:var(--portal-panel2);line-height:1.7}.identity-summary span{color:var(--portal-muted)}

/* Shared controls and plugin compatibility surfaces */
.card{background:var(--portal-panel)!important;border:1px solid var(--portal-line)!important;border-radius:var(--portal-radius)!important;padding:18px!important;box-shadow:var(--portal-shadow)!important;color:var(--portal-text)!important;overflow:hidden}.card:before{content:none!important}.grid{display:grid!important;grid-template-columns:repeat(12,minmax(0,1fr))!important;gap:14px!important}.span-3{grid-column:span 3}.span-4{grid-column:span 4}.span-5{grid-column:span 5}.span-6{grid-column:span 6}.span-7{grid-column:span 7}.span-8{grid-column:span 8}.span-12{grid-column:1/-1}.core-grid{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(320px,.9fr);gap:16px}
.list{display:grid!important;gap:9px!important}.item{border:1px solid var(--portal-line)!important;border-radius:12px!important;background:var(--portal-panel2)!important;padding:13px!important;color:var(--portal-text)!important}.item-title,.metric-value,.card h2,.card h3{color:var(--portal-text)!important}.item-meta,.metric-label,.metric-sub{color:var(--portal-muted)!important}.empty{border:1px dashed var(--portal-line-strong)!important;border-radius:12px!important;color:var(--portal-muted)!important;background:transparent!important;padding:24px 12px!important}
.btn{min-height:var(--portal-control)!important;border:1px solid var(--portal-line)!important;border-radius:10px!important;background:var(--portal-panel2)!important;color:var(--portal-text)!important;padding:9px 13px!important;font-weight:760!important;cursor:pointer!important;box-shadow:none!important}.btn:hover{border-color:var(--portal-line-strong)!important;background:var(--portal-panel3)!important}.btn.primary{background:linear-gradient(115deg,var(--portal-primary),var(--portal-primary2))!important;border-color:transparent!important;color:#fff!important}.btn.ghost{background:transparent!important}.btn.danger{background:color-mix(in srgb,var(--portal-bad) 9%,var(--portal-panel))!important;color:var(--portal-bad)!important}.btn:disabled{opacity:.45!important;cursor:not-allowed!important}
.field{min-width:0!important}.field label{color:var(--portal-muted)!important;font-size:11px!important}.field input,.field select,.field textarea,.qqai-modal-input,.top-actions select,.portal-header-actions select{width:100%!important;min-height:var(--portal-control)!important;border:1px solid var(--portal-line)!important;background:var(--portal-panel)!important;color:var(--portal-text)!important;border-radius:10px!important;box-shadow:none!important}.field input:focus,.field select:focus,.field textarea:focus,.qqai-modal-input:focus{border-color:var(--portal-primary)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--portal-primary) 13%,transparent)!important;outline:none!important}.field textarea{min-height:108px!important}select option{background:var(--portal-panel)!important;color:var(--portal-text)!important}
.notice{border:1px solid var(--portal-line)!important;border-radius:11px!important;background:var(--portal-panel2)!important;color:var(--portal-muted)!important}.pill{background:var(--portal-primary-soft)!important;color:var(--portal-primary-text)!important;border:1px solid color-mix(in srgb,var(--portal-primary) 18%,var(--portal-line))!important}.status{background:var(--portal-panel2)!important;color:var(--portal-muted)!important;border:1px solid var(--portal-line)!important}.status.ok{color:var(--portal-ok)!important}.status.warning{color:var(--portal-warn)!important}.status.error{color:var(--portal-bad)!important}
.code,pre,.log-details pre,.conversation-detail pre,.suite-decision-detail{max-width:100%!important;overflow:auto!important;background:var(--portal-panel2)!important;color:var(--portal-text)!important;border:1px solid var(--portal-line)!important;border-radius:10px!important}table{width:100%;border-collapse:separate!important;border-spacing:0!important;border:1px solid var(--portal-line)!important;border-radius:12px!important;overflow:hidden!important;background:var(--portal-panel)!important}th,td{padding:10px 11px!important;border-bottom:1px solid var(--portal-line)!important;color:var(--portal-text)!important}th{background:var(--portal-panel2)!important;color:var(--portal-muted)!important}tr:last-child td{border-bottom:0!important}details,.settings-fold{border:1px solid var(--portal-line)!important;background:var(--portal-panel)!important;border-radius:12px!important}summary{color:var(--portal-text)!important}
.qqai-modal{background:rgba(5,8,14,.60)!important;backdrop-filter:blur(8px)!important}.qqai-modal-card{background:var(--portal-panel)!important;color:var(--portal-text)!important;border:1px solid var(--portal-line)!important;box-shadow:var(--portal-shadow-lg)!important}.toast,#qqai-deployment-toast{background:var(--portal-text)!important;color:var(--portal-bg)!important;border:0!important;box-shadow:var(--portal-shadow-lg)!important}
.health-grid{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(240px,1fr))!important;gap:11px!important}.health-card{border:1px solid var(--portal-line)!important;border-radius:12px!important;background:var(--portal-panel2)!important}.switch input,.member-toggle input{accent-color:var(--portal-primary)!important}
.member-console-toolbar{grid-template-columns:minmax(220px,.9fr) minmax(280px,1.1fr)!important}.member-console-filters{grid-template-columns:repeat(4,minmax(150px,1fr)) auto auto!important}.member-directory-row{grid-template-columns:minmax(220px,1.35fr) minmax(190px,.75fr) auto!important}.member-action-row{grid-template-columns:minmax(220px,1fr) minmax(190px,.7fr) minmax(360px,1.45fr)!important}.relationship-direct{grid-template-columns:repeat(2,minmax(200px,1fr)) auto auto!important}.relationship-row{grid-template-columns:minmax(240px,1fr) auto!important}.suite-grid{grid-template-columns:repeat(auto-fit,minmax(210px,1fr))!important}.suite-batch-controls,.suite-sticker-form,.suite-decision-filters,.suite-profile-flags{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(170px,1fr))!important;gap:10px!important}.cleanup-summary{grid-template-columns:repeat(auto-fit,minmax(130px,1fr))!important}.cleanup-policy{grid-template-columns:repeat(auto-fit,minmax(165px,1fr))!important}.cleanup-filters,.member-data-toolbar,.cleanup-head-actions{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(180px,1fr))!important;gap:10px!important}.ops-integrated-block{margin-top:16px!important}
@media(max-width:1120px){.portal-appbar-inner{grid-template-columns:auto 1fr}.portal-header-actions{grid-column:1/-1;justify-content:flex-end;padding-bottom:8px}.portal-primary-nav{justify-content:flex-end!important}.portal-home-grid,.core-grid{grid-template-columns:1fr}.portal-core-status{grid-template-columns:1fr 1fr 1fr}.plugin-grid.compact{grid-template-columns:1fr}.span-3,.span-4,.span-5,.span-6,.span-7,.span-8{grid-column:span 6!important}}
@media(max-width:1024px){body.sidebar-open{overflow:hidden!important}.portal-appbar-inner{min-height:66px;grid-template-columns:auto auto 1fr;gap:10px}.portal-menu{display:inline-flex!important;grid-column:2}.portal-primary-nav{display:none!important;position:absolute!important;left:16px!important;right:16px!important;top:66px!important;z-index:65!important;padding:10px!important;border:1px solid var(--portal-line)!important;border-radius:15px!important;background:var(--portal-panel)!important;box-shadow:var(--portal-shadow-lg)!important;flex-direction:column!important;align-items:stretch!important}.portal-appbar.open .portal-primary-nav{display:flex!important}.portal-primary-nav>button[data-view]{width:100%;text-align:left}.portal-header-actions{grid-column:3;grid-row:1;justify-content:flex-end;padding:0}.portal-header-actions .identity-card,.portal-rights{display:none}.portal-header-actions select{width:110px!important}.portal-logout{display:none!important}.sidebar-backdrop.open{display:block!important;position:fixed;inset:66px 0 0;z-index:50;background:rgba(4,7,12,.50);backdrop-filter:blur(3px)}.portal-subbar,.topbar{width:min(100% - 24px,1480px)!important;padding-top:17px!important}.portal-content,.content{width:min(100% - 24px,1480px)!important;padding-bottom:38px!important}.portal-home-hero{grid-template-columns:1fr;min-height:auto}.portal-home-orbit{min-height:260px}.portal-core-status{grid-template-columns:1fr}.span-3,.span-4,.span-5,.span-6,.span-7,.span-8,.span-12{grid-column:1/-1!important}.member-console-toolbar,.member-console-filters,.member-directory-row,.member-action-row,.relationship-direct,.relationship-row,.cleanup-row,.member-data-row{grid-template-columns:1fr!important}}
@media(max-width:700px){.portal-appbar-inner{width:min(100% - 18px,1480px);grid-template-columns:auto auto 1fr}.portal-brand small{display:none}.portal-brand b{font-size:12px}.portal-brand-logo{width:38px;height:38px}.portal-header-actions select{display:none}.portal-header-actions .theme-toggle{min-width:46px;padding-inline:8px!important;font-size:0}.portal-header-actions .theme-toggle:after{content:"◐";font-size:15px}.portal-home-hero{padding:24px;border-radius:20px}.portal-home-copy h1{font-size:40px}.portal-home-orbit{display:none}.portal-home-grid{grid-template-columns:1fr}.plugin-grid{grid-template-columns:1fr}.plugin-card{grid-template-columns:42px minmax(0,1fr)}.plugin-card>.plugin-actions{grid-column:1/-1;width:100%;justify-content:stretch}.plugin-card>.plugin-actions .btn{flex:1}.section-head{display:grid!important}.portal-subbar,.topbar{display:grid!important;align-items:start!important}.top-actions{justify-content:stretch!important}.top-actions>*{width:100%!important}.member-actions,.relationship-actions{display:grid!important;grid-template-columns:1fr!important}.suite-batch-controls,.suite-sticker-form,.suite-decision-filters,.suite-profile-flags,.cleanup-filters,.member-data-toolbar,.cleanup-head-actions{grid-template-columns:1fr!important}}
@media(max-width:440px){.portal-home-copy h1{font-size:34px}.portal-home-actions .btn{width:100%}.card{padding:14px!important}.portal-status-card{padding:13px}.portal-page-heading h2{font-size:19px}}
</style>`;
  const script = `<script id="qqai-portal-layout-client-v400">(function(){document.documentElement.dataset.portalLayout="4.0.0";})();</script>`;
  source = source.includes("</head>") ? source.replace("</head>", style + "\n</head>") : style + source;
  source = source.includes("</body>") ? source.replace("</body>", script + "\n</body>") : source + script;
  return source;
}

export { injectPortalLayoutClient };
