import { createCommandRegistry } from "./registry.js";

const INITIAL_COMMANDS = Object.freeze([
  { id:"core.help", aliases:["!help","!帮助","!幫助"], scopes:["c2c","group"], description:"查看可用指令", category:"core", menu:{enabled:true,name:"帮助"}, panel:{enter:true} },
  { id:"core.status", aliases:["!status","!配额","!配額"], scopes:["c2c","group"], description:"查看系统与额度状态", category:"core", menu:{enabled:true,name:"状态"}, panel:{enter:true} },
  { id:"ai.codex", aliases:["!codex"], scopes:["c2c","group"], description:"Codex 对话", category:"ai", menu:{enabled:true,name:"Codex"} },
  { id:"ai.codexchat", aliases:["!codexchat"], scopes:["c2c","group"], permission:"developer", description:"开发者 Codex 对话", category:"ai" },
  { id:"ai.codexwork", aliases:["!codexwork"], scopes:["c2c","group"], permission:"developer", description:"受限本机工作区", category:"ai" },
  { id:"ai.model", aliases:["!模型"], scopes:["c2c","group"], description:"切换个人模型", category:"ai", menu:{enabled:true,name:"模型"} },
  { id:"qq.voice_roles", aliases:["!QQ语音角色","!QQ語音角色"], scopes:["c2c","group"], description:"查看 QQ 语音角色", category:"multimodal", panel:{enter:true} },
  { id:"qq.voice_reply", aliases:["!QQ语音","!QQ語音"], scopes:["c2c","group"], description:"使用 QQ 语音角色回复", category:"multimodal" },
  { id:"group.status", aliases:["!群状态","!群狀態"], scopes:["group"], description:"查看群 AI 状态", category:"group", menu:{enabled:true,name:"群状态"}, panel:{enter:true} },
  { id:"group.rules", aliases:["!群规","!群規","!rules"], scopes:["group"], description:"查看群规", category:"group", menu:{enabled:true,name:"群规"}, panel:{enter:true} },
  { id:"member.speech", aliases:["!成员发言分析","!成員發言分析"], scopes:["group"], description:"分析成员近期发言", category:"member" },
  { id:"member.details", aliases:["!详细资料","!詳細資料"], scopes:["group"], description:"查询成员资料", category:"member" },
  { id:"group.mute", aliases:["!禁言"], scopes:["group"], permission:"group_ops", description:"禁言指定成员", category:"moderation", panel:{onlyAdmin:true} },
  { id:"group.unmute", aliases:["!解禁"], scopes:["group"], permission:"group_ops", description:"解除成员禁言", category:"moderation", panel:{onlyAdmin:true} },
  { id:"group.recall", aliases:["!撤回"], scopes:["group"], permission:"group_ops", description:"撤回目标消息", category:"moderation", panel:{onlyAdmin:true} },
  { id:"group.kick", aliases:["!踢出"], scopes:["group"], permission:"group_ops", description:"移出指定成员", category:"moderation", panel:{onlyAdmin:true} },
  { id:"group.mute_all", aliases:["!全员禁言","!全員禁言"], scopes:["group"], permission:"group_ops", description:"开启全员禁言", category:"moderation", panel:{onlyAdmin:true,enter:true} },
  { id:"group.unmute_all", aliases:["!解除全员禁言","!解除全員禁言"], scopes:["group"], permission:"group_ops", description:"解除全员禁言", category:"moderation", panel:{onlyAdmin:true,enter:true} },
  { id:"memory.remember", aliases:["!记住","!記住"], scopes:["c2c","group"], description:"保存记忆", category:"memory" },
  { id:"memory.forget", aliases:["!忘记","!忘記"], scopes:["c2c","group"], description:"删除指定记忆", category:"memory" },
  { id:"user.dnd", aliases:["!免打扰","!免打擾"], scopes:["c2c","group"], description:"开启免打扰", category:"user", panel:{enter:true} },
  { id:"user.dnd_off", aliases:["!取消免打扰","!取消免打擾"], scopes:["c2c","group"], description:"关闭免打扰", category:"user", panel:{enter:true} },
  { id:"tool.web", aliases:["!读网页","!讀網頁"], scopes:["c2c","group"], description:"读取公开网页并摘要", category:"tool" },
  { id:"tool.translate", aliases:["!翻译","!翻譯"], scopes:["c2c","group"], description:"翻译文字", category:"tool" },
  { id:"memory.list", aliases:["!你记住了什么","!你記住了什麼"], scopes:["c2c","group"], description:"查看已保存记忆", category:"memory", panel:{enter:true} },
  { id:"persona.set", aliases:["!set人格"], scopes:["c2c","group"], description:"设置个人或群人格", category:"persona" },
  { id:"persona.delete", aliases:["!del人格"], scopes:["c2c","group"], description:"删除个人或群人格", category:"persona", panel:{enter:true} },
  { id:"message.recall_help", aliases:["!协助撤回","!協助撤回"], scopes:["group"], description:"协助撤回自己的消息", category:"message" },
  { id:"event.activity", aliases:["!活动","!活動"], scopes:["group"], description:"建立或查看活动", category:"event" },
  { id:"event.signup", aliases:["!报名","!報名"], scopes:["group"], description:"报名活动", category:"event" },
  { id:"event.signup_cancel", aliases:["!取消报名","!取消報名"], scopes:["group"], description:"取消活动报名", category:"event" },
  { id:"event.roster", aliases:["!活动名单","!活動名單"], scopes:["group"], description:"查看活动名单", category:"event" },
  { id:"event.notify", aliases:["!活动通知","!活動通知"], scopes:["group"], description:"发送活动通知", category:"event" },
  { id:"event.vote", aliases:["!投票"], scopes:["group"], description:"建立或管理投票", category:"event" },
  { id:"schedule.manage", aliases:["!排程"], scopes:["c2c","group"], description:"建立、查看或取消排程", category:"schedule" },
  { id:"appeal.create", aliases:["!申诉","!申訴"], scopes:["c2c"], description:"提交群管理申诉", category:"appeal" },
  { id:"rules.inspect", aliases:["!检查","!檢查"], scopes:["group"], description:"人工补检目标消息", category:"rules" },
  { id:"rules.no_violation", aliases:["!无违规","!無違規"], scopes:["group"], permission:"group_ops", description:"撤销最近误判", category:"rules", panel:{onlyAdmin:true} },
  { id:"ai.off", aliases:["!关闭ai","!關閉ai"], scopes:["group"], permission:"ai_admin", description:"关闭本群 AI", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"ai.on", aliases:["!开启ai","!開啟ai"], scopes:["group"], permission:"ai_admin", description:"开启本群 AI", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"memory.on", aliases:["!记忆开","!記憶開"], scopes:["group"], permission:"ai_admin", description:"开启群记忆", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"memory.off", aliases:["!记忆关","!記憶關"], scopes:["group"], permission:"ai_admin", description:"关闭群记忆", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"ai.blacklist", aliases:["!拉黑"], scopes:["group"], permission:"ai_admin", description:"加入 AI 黑名单", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"ai.unblacklist", aliases:["!解除拉黑"], scopes:["group"], permission:"ai_admin", description:"解除 AI 黑名单", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"rules.set", aliases:["!set群规","!set群規"], scopes:["group"], permission:"ai_admin", description:"设置群规", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"rules.monitor", aliases:["!群规监控","!群規監控"], scopes:["group"], permission:"ai_admin", description:"设置群规监控", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"rules.agent", aliases:["!AI群规代理","!AI群規代理"], scopes:["group"], permission:"ai_admin", description:"设置 AI 群规代理", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"rules.strictness", aliases:["!群规严格度","!群規嚴格度"], scopes:["group"], permission:"ai_admin", description:"设置群规严格度", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"rules.mute_protect", aliases:["!违规禁言保护","!違規禁言保護"], scopes:["group"], permission:"ai_admin", description:"设置违规禁言保护", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"persona.group_set", aliases:["!切换人格","!切換人格"], scopes:["group"], permission:"ai_admin", description:"切换群人格", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"persona.group_reset", aliases:["!恢复人格","!恢復人格"], scopes:["group"], permission:"ai_admin", description:"恢复群人格", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"welcome.auto", aliases:["!自动欢迎","!自動歡迎"], scopes:["group"], permission:"ai_admin", description:"设置自动欢迎", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"welcome.text", aliases:["!欢迎词","!歡迎詞"], scopes:["group"], permission:"ai_admin", description:"设置欢迎词", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"join.assist", aliases:["!入群辅助","!入群輔助"], scopes:["group"], permission:"ai_admin", description:"设置入群辅助", category:"ai_admin", panel:{onlyAdmin:true} },
  { id:"commands.on", aliases:["!指令开","!指令開"], scopes:["group"], permission:"ai_admin", description:"开启群指令", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"commands.off", aliases:["!指令关","!指令關"], scopes:["group"], permission:"ai_admin", description:"关闭群指令", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"context.clear_group", aliases:["!清空群上下文","!清除群上下文"], scopes:["group"], permission:"ai_admin", description:"清空群短期上下文", category:"ai_admin", panel:{onlyAdmin:true,enter:true} },
  { id:"group.rename", aliases:["!改群名"], scopes:["group"], permission:"group_ops", description:"修改群名称", category:"moderation", panel:{onlyAdmin:true} },
  { id:"group.card", aliases:["!改名片"], scopes:["group"], permission:"group_ops", description:"修改成员群名片", category:"moderation", panel:{onlyAdmin:true} },
  { id:"group.confirm", aliases:["!确认op","!確認op"], scopes:["group"], permission:"group_ops", description:"确认最新群操作提案", category:"moderation", panel:{onlyAdmin:true,enter:true} },
  { id:"group.cancel", aliases:["!取消op"], scopes:["group"], permission:"group_ops", description:"取消最新群操作提案", category:"moderation", panel:{onlyAdmin:true,enter:true} },
  { id:"owner.kick_auth", aliases:["!授权AI踢出","!授權AI踢出"], scopes:["group"], permission:"owner", description:"授权 AI 踢出", category:"owner", panel:{onlyAdmin:true,enter:true} },
  { id:"owner.kick_revoke", aliases:["!撤回AI踢出授权","!撤回AI踢出授權","!撤回AI踢出"], scopes:["group"], permission:"owner", description:"撤回 AI 踢出授权", category:"owner", panel:{onlyAdmin:true,command:"!撤回AI踢出",enter:true} },
  { id:"owner.reject_auth", aliases:["!授权AI拒绝入群","!授權AI拒絕入群","!授权AI拒入群"], scopes:["group"], permission:"owner", description:"授权 AI 拒绝入群", category:"owner", panel:{onlyAdmin:true,command:"!授权AI拒入群",enter:true} },
  { id:"owner.reject_revoke", aliases:["!撤回AI拒绝入群授权","!撤回AI拒絕入群授權","!撤回AI拒绝入群","!撤回AI拒絕入群","!撤回AI拒入群"], scopes:["group"], permission:"owner", description:"撤回 AI 拒绝入群授权", category:"owner", panel:{onlyAdmin:true,command:"!撤回AI拒入群",enter:true} },
  { id:"owner.cooldown", aliases:["!设置处置冷却","!設定處置冷卻"], scopes:["group"], permission:"owner", description:"设置处置冷却", category:"owner", panel:{onlyAdmin:true} },
  { id:"owner.newcomer", aliases:["!设置新人观察期","!設定新人觀察期","!设置新人期"], scopes:["group"], permission:"owner", description:"设置新人观察期", category:"owner", panel:{onlyAdmin:true,command:"!设置新人期"} },
  { id:"owner.cancel_use", aliases:["!取消使用"], scopes:["group"], permission:"owner", description:"结束全群模仿覆盖", category:"owner", panel:{onlyAdmin:true,enter:true} },
  { id:"dev.group_allow", aliases:["!群白名单","!群白名單"], scopes:["c2c","group"], permission:"developer", description:"加入群白名单", category:"developer" },
  { id:"dev.group_deny", aliases:["!删群白名单","!刪群白名單"], scopes:["c2c","group"], permission:"developer", description:"删除群白名单", category:"developer" },
  { id:"dev.grant", aliases:["!授权","!授權"], scopes:["group"], permission:"developer", description:"授予程序权限", category:"developer" },
  { id:"dev.revoke", aliases:["!撤销授权","!撤銷授權"], scopes:["group"], permission:"developer", description:"撤销程序权限", category:"developer" },
  { id:"dev.memory_ban", aliases:["!禁记忆","!禁記憶"], scopes:["group"], permission:"developer", description:"禁止成员写入记忆", category:"developer" },
  { id:"dev.memory_unban", aliases:["!解禁记忆","!解禁記憶"], scopes:["group"], permission:"developer", description:"解除记忆禁止", category:"developer" },
  { id:"dev.reset", aliases:["!重置","!clear"], scopes:["c2c","group"], permission:"developer", description:"重置当前上下文", category:"developer", panel:{enter:true} },
  { id:"dev.self_adjust", aliases:["!自我调整","!自我調整"], scopes:["c2c","group"], permission:"developer", description:"执行自我调整", category:"developer", panel:{enter:true} },
  { id:"dev.self_correct", aliases:["!自我修正"], scopes:["c2c","group"], permission:"developer", description:"执行自我修正", category:"developer", panel:{enter:true} }
]);

function createInitialCommandRegistry() { return createCommandRegistry(INITIAL_COMMANDS); }
export { INITIAL_COMMANDS, createInitialCommandRegistry };
